name: Deploy to Docker Nginx

on:
  push:
    branches:
      - main  # 或你的主分支

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

      #测试修改
    - name: Scp to server and deploy
      uses: appleboy/scp-action@v0.0.1
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.PRIVATE_KEY }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        source: "../*.html"
        target: ${{ secrets.SERVER_TARGET }}
        
